name: expresshealth
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_floating_search_bar: ^0.3.4
  intl: ^0.17.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_launcher_icons: ^0.9.2
  country_codes: ^2.1.1
  country_code_picker: ^2.0.2
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: ^0.9.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


#flutter_icons:
#  android: true
#  iso: true
#  image_path: "assets/icons/logo/E-Health.png"


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/edit.png
    - assets/icons/chat.png
    - assets/icons/drugs.png
    - assets/icons/eye-open.png
    - assets/icons/heart.png
    - assets/icons/medical.png
    - assets/icons/molar.png
    - assets/icons/down-arrow.png
    - assets/icons/like.png
    - assets/icons/message.png
    - assets/icons/up-arrow.png
    - assets/icons/medicalw.png
    - assets/icons/video-camera.png
    - assets/images/img.jpg
    - assets/images/sdf.jpg
    - assets/images/ddf.png
    - assets/icons/add-pic.png
    # - assets/images/michael_obeng.png
    - assets/images/firstimg.webp
    - assets/images/secondimg.jpg
    - assets/images/third.jpg
    - assets/images/fourthimg.jpg
    - assets/images/sixthimg.jpg
    - assets/images/seventhimg.jpg
    - assets/images/ninthimg.jpg
    - assets/images/bgimg1.jpg
    - assets/images/bgimg2.webp
    - assets/images/bgimg3.jpg
    - assets/images/bgimg4.jpg
    - assets/images/bgimg5.jpg
    - assets/images/bgimg6.jpg
    - assets/images/bgimg7.jpg
    - assets/images/bgimg8.jpg
    - assets/login_icon/timg.jpeg
    - assets/login_icon/adimg.jpeg
    - assets/login_icon/lo.jpg
    - assets/login_icon/fit.jpg
    - assets/login_icon/Capt.jpg
    - assets/login_icon/18083.png
    - assets/login_icon/45.png
    - assets/icons/funnel.png
    - assets/icons/drug1.png
    - assets/icons/logo/E-Health.png
    - assets/icons/headphones.png
    - assets/icons/comment.png
    - assets/images/BG1.png


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/NexaLight.otf
        - asset: assets/fonts/NexaBold.otf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
